/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#46464a",
        "outline-variant": "#c7c6ca",
        "inverse-primary": "#c8c6c8",
        "on-error-container": "#93000a",
        "primary-fixed": "#e4e2e4",
        outline: "#77767b",
        "on-error": "#ffffff",
        "surface-container-highest": "#e2e2e4",
        "inverse-surface": "#2f3132",
        "on-tertiary-fixed": "#1a1c1f",
        "on-surface": "#1a1c1d",
        "surface-variant": "#e2e2e4",
        "surface-container-high": "#e8e8ea",
        "on-secondary-container": "#626267",
        "surface-container": "#edeef0",
        "inverse-on-surface": "#f0f0f2",
        secondary: "#5e5e63",
        tertiary: "#020304",
        "on-background": "#1a1c1d",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#c7c6cb",
        "primary-container": "#1d1d1f",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9fb",
        "tertiary-fixed": "#e2e2e7",
        "surface-tint": "#5f5e60",
        "surface-container-low": "#f3f3f5",
        "secondary-fixed": "#e3e2e7",
        primary: "#030304",
        "error-container": "#ffdad6",
        background: "#f9f9fb",
        "on-primary-container": "#868587",
        "on-primary-fixed-variant": "#474649",
        "tertiary-fixed-dim": "#c6c6cb",
        "on-tertiary-fixed-variant": "#45474b",
        "on-secondary-fixed": "#1a1b1f",
        "secondary-container": "#e0dfe4",
        surface: "#f9f9fb",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#848589",
        "on-secondary": "#ffffff",
        "tertiary-container": "#1b1d21",
        "primary-fixed-dim": "#c8c6c8",
        "on-secondary-fixed-variant": "#46464b",
        error: "#ba1a1a",
        "surface-dim": "#d9dadc",
        "on-primary-fixed": "#1b1b1d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "stack-md": "16px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max-width": "1200px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        gutter: "24px",
        section: "120px",
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.03em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
